{% set version = "0.3" %}

package:
  name: easyprocess
  version: {{ version }}

source:
  fn: easyprocess-{{ version }}.tar.gz
  url: https://github.com/ponty/EasyProcess/archive/{{ version }}.tar.gz
  sha256: eea7f7f2074b599ca4cb2a14c098eb0a0e21f8886eb38c45b8c0b3cb89e7aff9

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python


test:
  imports:
    - easyprocess

about:
  home: https://github.com/ponty/EasyProcess
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: Easy to use python subprocess interface

extra:
  recipe-maintainers:
    - ReimarBauer
