{% set version = "0.2.7" %}

package:
  name: easyprocess
  version: {{ version }}

source:
  fn: easyprocess-{{ version }}.tar.gz
  url:  https://github.com/ponty/EasyProcess/archive/{{version}}.tar.gz
  sha256: 88ca68b462b0e44f673e64ccfab535a88d35aea0a85f23bfee60089de8b4fda8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    

test:
  imports:
    - easyprocess

about:
  home: https://github.com/ponty/EasyProcess
  license: BSD 2-clause 
  license_file: LICENSE.txt
  summary: 'Easy to use python subprocess interface'

extra:
  recipe-maintainers:
    - ReimarBauer
